name: Dispatch CI

on:
  # At 8:40 PM UTC, only on Monday and Tuesday
  schedule:
    - cron: '40 20 * * 1,2'

permissions: {}

jobs:
  dispatch-ci:
    name: Dispatch CI
    # Only run cron on the bringyourownideas account
    if: (github.event_name == 'schedule' && github.repository_owner == 'bringyourownideas') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Dispatch CI
        uses: silverstripe/gha-dispatch-ci@v1
